export const consts = {
  DEBUG: import.meta.env.VITE_DEBUG === 'true',
  DOMAIN: import.meta.env.VITE_DOMAIN,
  PURIFY_LOG_ERRORS: import.meta.env.VITE_PURIFY_LOG_ERRORS === 'true',
  PURIFY_EXTERNAL_LINK_PREFIXES: [
    'http',  // allow any HTTP link
  ],
  PURIFY_ALLOWED_TAGS: 'a blockquote body br code em h1 h2 h3 h4 h5 h6 hr img li ol p pre span strong table tbody td th thead tr ul #text'.split(' '),
  PURIFY_ALLOWED_ATTR: 'alt class href src style title'.split(' '),
  OPERATIONS_PANEL_MIN_VALUE: 10,
  OPERATIONS_PANEL_MAX_VALUE: 33,
  OPERATIONS_PANEL_DEFAULT_VALUE: 15,
  IO_PANEL_MIN_VALUE: 20,
  IO_PANEL_MAX_VALUE: 66,
  IO_PANEL_DEFAULT_VALUE: 30,
  INPUT_HEIGHT_MIN_VALUE: 10,
  INPUT_HEIGHT_MAX_VALUE: 90,
  INPUT_HEIGHT_DEFAULT_VALUE: 50,
  BAKING_DELAY_MIN_VALUE: 50,
  BAKING_DELAY_MAX_VALUE: 10_000,
  BAKING_DELAY_DEFAULT_VALUE: 250,
  UPDATE_URL_DELAY: 50,
  HACK_MD_DOMAIN: "https://hackmd.io",
  GITHUB_DOMAIN: "https://github.com",
  GITHUB_API_DOMAIN: "https://api.github.com",
  SHORT_LINKS_DEFAULT_DOMAIN: "https://asp-chef.alviano.net",
  SHORT_LINKS_DEFAULT_USERNAME: "alviano",
  SHORT_LINKS_DEFAULT_REPOSITORY: "asp-chef-short-links",
  CDN_JSDELIVER_DOMAIN: "https://cdn.jsdelivr.net",
  NPM_DOMAIN: "https://www.npmjs.com/",
  SYMBOLS: {
    CHECK_MARK: '✔',
    CROSS_MARK: '✘',
    CRYING_FACE: '😢',
    THUMB_UP: '👍',
    LOCKED: '🔒',
    UNLOCKED: '🔓',
    MODELS_SEPARATOR: '§',
    SEARCH_FAIL: '§',
    NEW_LINE: '⏎',
  },
};
